# This is a basic workflow to help you get started with Actions

name: CI Java Maven Build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Clone Repository
        with:
          repository: 'nadeemahmed93/sample-dockerised-java-app@v1.0.0'
          ref: 'master'
